---
- name: Install cerbot
  ansible.builtin.package:
    name: certbot
    state: present
  become: true
  tags:
    - certbot_install

- name: Make renewal-hooks directory
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  become: true
  tags:
    - certbot_setup

- name: Make renewal-hooks directory
  ansible.builtin.file:
    path: "/etc/letsencrypt/renewal-hooks/{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  become: true
  loop:
    - pre
    - post
  tags:
    - certbot_setup

- name: Template pre- and post-hooks
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "/etc/letsencrypt/renewal-hooks/{{ item.file }}"
    mode: u=rwx,g=x,o=x
    owner: root
    group: root
  become: true
  when: item.slug in certbot_hooks
  loop:
    # enforce ordering using debian configuration file  style
    - {file: "pre/20-open_firewall_http", slug: nftables}
    - {file: "post/20-close_firewall_http", slug: nftables}
    - {file: "pre/10-stop_nginx", slug: nginx}
    - {file: "post/10-start_nginx", slug: nginx}
  tags:
    - certbot_update

- name: Template hook scripts
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "/etc/letsencrypt/renewal-hooks/{{ item.file }}"
    mode: u=rwx,g=x,o=x
    owner: root
    group: root
  become: true
  loop:
    # enforce ordering using debian configuration file  style
    - {file: "pre/hooks"}
    - {file: "post/hooks"}
  tags:
    - certbot_update

- name: Move certbot service and validate
  tags:
    - certbot_update
  block:
    - name: Move certbot service to host
      ansible.builtin.template:
        src: certbot.service
        dest: /lib/systemd/system/certbot.service
        # does not work using Ansible
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true
      register: cerbot_template
      notify: "reload systemd"

    - name: Validate certbot service
      ansible.builtin.command: systemd-analyze verify certbot.service
      args:
        chdir: "/lib/systemd/system"
      changed_when: false
      become: true

- name: Template config file
  ansible.builtin.template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: u=rw,g=r,o=r
    owner: root
    group: root
  become: true
  notify: "enable certbot timer"
  tags:
    - certbot_update
